// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUyPlUiWE0P_7QyscejMGEG0kl-fsJDA',
    appId: '1:902799490937:web:19fe93346a251646f039a8',
    messagingSenderId: '902799490937',
    projectId: 'pinkchatapplication',
    authDomain: 'pinkchatapplication.firebaseapp.com',
    storageBucket: 'pinkchatapplication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXuTnhVFQbbTLu1IecACwUPXivexqTKUs',
    appId: '1:902799490937:android:721f21bb7b9a28c3f039a8',
    messagingSenderId: '902799490937',
    projectId: 'pinkchatapplication',
    storageBucket: 'pinkchatapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiTDiHFCPcoOGip3lFfkIj0PdkS6m3djY',
    appId: '1:902799490937:ios:8cc1519acdd51efff039a8',
    messagingSenderId: '902799490937',
    projectId: 'pinkchatapplication',
    storageBucket: 'pinkchatapplication.firebasestorage.app',
    iosBundleId: 'com.example.pinkchatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiTDiHFCPcoOGip3lFfkIj0PdkS6m3djY',
    appId: '1:902799490937:ios:8cc1519acdd51efff039a8',
    messagingSenderId: '902799490937',
    projectId: 'pinkchatapplication',
    storageBucket: 'pinkchatapplication.firebasestorage.app',
    iosBundleId: 'com.example.pinkchatapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGUyPlUiWE0P_7QyscejMGEG0kl-fsJDA',
    appId: '1:902799490937:web:7f8456f9474e1678f039a8',
    messagingSenderId: '902799490937',
    projectId: 'pinkchatapplication',
    authDomain: 'pinkchatapplication.firebaseapp.com',
    storageBucket: 'pinkchatapplication.firebasestorage.app',
  );
}
